name: backup-kb

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip KB & Core
        # ← 生成と同時に ZIP の実パスを表示する
        run: |
          mkdir -p dist
          ZIP="dist/kb_backup_${GITHUB_SHA}.zip"
          echo "ZIP PATH: $ZIP"
          zip -r "$ZIP" kb system/core.yaml

      - name: List files (debug)
        # ← dist 内に ZIP が実在するか一覧表示（確認の決め手）
        run: ls -al dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # ← タグとリリース名はコミットSHAでユニーク化
          tag_name: backup-${{ github.sha }}
          name: backup-${{ github.sha }}
          make_latest: false
          # ← 上で作った ZIP と完全一致させる（同じ GITHUB_SHA を使用）
          files: dist/kb_backup_${{ github.sha }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
